### ISSUE TITLE
Funk is being re-triggered, but isn't on_save

### ISSUE THREAD

**Issue by toomim** [TheInvisibles/statebus#26]
This happens on slideboard:
```
Uncaught Exception:
AssertionError: Funk is being re-triggered, but isn't on_save. It is: "to_forget", oh and funk: function get_from_master("post/w72p51v3p6x6vg6i529") {..}
    at Console.assert (console.js:94:23)
    at Function.run_handler (/home/considerit/Dropbox/ConsiderIt/prototypes/slideboard/node_modules/statebus/statebus.js:723:21)
    at bus.route (/home/considerit/Dropbox/ConsiderIt/prototypes/slideboard/node_modules/statebus/statebus.js:852:17)
    at Function.bus.route (/home/considerit/Dropbox/ConsiderIt/prototypes/slideboard/node_modules/statebus/server.js:1029:25)
    at Timeout._onTimeout (/home/considerit/Dropbox/ConsiderIt/prototypes/slideboard/node_modules/statebus/statebus.js:391:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```
We don't have a reproducible testcase yet, but haven't tried to make one. It seems pretty frequent.

**Comment by tkriplean** [comment]
I have code that is consistently triggering this error. I haven't isolated the offending code. Here's where you can see the code and error: 

The code is in Dropbox/Considerit/prototypes/reputation. The offending code is in client/reputation.coffee. 

The server is running using supervisor in a screen session on our linode (screen -r reputation). 

If you load http://considerit.us:3439, the server will frequently crash with the above error, restart, then crash again.

**Comment by toomim** [comment]
Thank you! Looks like I'll have to get into this one. Do you happen to know if it is always a "to_forget" on "get_from_master(...)"? If so, I think I see a path for debugging it.

**Comment by tkriplean** [comment]
I think it is always "to_forget". I'll keep an eye on that. Let me know if you want me to try to create a smaller test case.

**Comment by toomim** [comment]
Ok thanks. Don't put further work into it yet.

**Comment by toomim** [comment]
Is this causing any problems with current stuff? Like, should I try to fix it?

**Comment by toomim** [comment]
Travis is also getting this now:

```
Uncaught Exception:
AssertionError: Funk is being re-triggered, but isn't on_save. It is: "to_forget", oh and funk: **function sockjs_pubber({"all":[{"client":"61bfc343-6e) {..}**
    at Console.assert (console.js:94:23)
    at Function.run_handler (/home/considerit/Dropbox/Invisible College/considerit-lab/node_modules/statebus/statebus.js:738:21)
    at bus.route (/home/considerit/Dropbox/Invisible College/considerit-lab/node_modules/statebus/statebus.js:901:17)
    at Function.bus.route (/home/considerit/Dropbox/Invisible College/considerit-lab/node_modules/statebus/server.js:1240:25)
    at Timeout._onTimeout (/home/considerit/Dropbox/Invisible College/considerit-lab/node_modules/statebus/statebus.js:389:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I haven't gotten around to investigating it yet.
